### ISSUE TITLE
Glib error

### ISSUE THREAD

**Issue by heikostark** [febiosoftware/FEBioStudio#17]
When running FEBioStudio, a memory violation occurs under Linux (5.7.19-desktop-1.mga7).

$ gdb FEBioStudio 
GNU gdb (GDB) 8.2-8.1.mga7 (Mageia release 7)
...

(gdb) run
Starting program: /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/FEBioStudio 
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
...

(process:8994): GLib-CRITICAL **: 20:00:39.014: g_hash_table_contains: assertion 'hash_table != NULL' failed
(process:8994): GLib-CRITICAL **: 20:00:39.014: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
Thread 1 "FEBioStudio" received signal SIGSEGV, Segmentation fault.
0x00007fffdf49fbc9 in g_wakeup_signal () from /usr/lib64/libglib-2.0.so.0
...

(gdb) bt
#0  0x00007fffdf49fbc9 in g_wakeup_signal () from /usr/lib64/libglib-2.0.so.0
#1  0x00007fffdf457676 in g_source_attach_unlocked () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fffdf458ffb in g_source_attach () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fffdd302167 in _ZN19QXcbEventDispatcher21createEventDispatcherEP14QXcbConnection () from /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007fffee2103e9 in _ZN22QGuiApplicationPrivate21createEventDispatcherEv () from /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/../lib/libQt5Gui.so.5
#5  0x00007fffed7bf3a6 in _ZN23QCoreApplicationPrivate4initEv () from /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/../lib/libQt5Core.so.5
#6  0x00007fffee212dfc in _ZN22QGuiApplicationPrivate4initEv () from /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/../lib/libQt5Gui.so.5
#7  0x00007fffeeb2d71e in _ZN19QApplicationPrivate4initEv () from /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/../lib/libQt5Widgets.so.5
#8  0x00000000004da5c7 in main ()

$ ldd FEBioStudio    
        linux-vdso.so.1 (0x00007ffe44b84000)
        libssh.so.4 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libssh.so.4 (0x00007f03dcea0000)
        libcrypto.so.1.1 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libcrypto.so.1.1 (0x00007f03dc9b0000)
        libssl.so.1.1 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libssl.so.1.1 (0x00007f03dc718000)
        libnglib.so => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libnglib.so (0x00007f03dc500000)
        libcsg.so => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libcsg.so (0x00007f03dc248000)
        libinterface.so => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libinterface.so (0x00007f03dbff0000)
        libmesh.so => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libmesh.so (0x00007f03dbb88000)
        libocc.so => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libocc.so (0x00007f03db900000)
        libTKernel.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKernel.so.7 (0x00007f03db548000)
        libTKGeomBase.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKGeomBase.so.7 (0x00007f03dae48000)
        libTKTopAlgo.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKTopAlgo.so.7 (0x00007f03da958000)
        libTKPrim.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKPrim.so.7 (0x00007f03da6f8000)
        libTKMesh.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKMesh.so.7 (0x00007f03da460000)
        libTKMath.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKMath.so.7 (0x00007f03da010000)
        libTKBRep.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKBRep.so.7 (0x00007f03d9d18000)
        libTKSTL.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKSTL.so.7 (0x00007f03d9b00000)
        libTKFillet.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKFillet.so.7 (0x00007f03d9688000)
        libTKBO.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKBO.so.7 (0x00007f03d9248000)
        libTKIGES.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKIGES.so.7 (0x00007f03d8c40000)
        libTKSTEP.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKSTEP.so.7 (0x00007f03d86e8000)
        libTKSTEPBase.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKSTEPBase.so.7 (0x00007f03d8248000)
        libTKXSBase.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKXSBase.so.7 (0x00007f03d7db0000)
        libTKG3d.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKG3d.so.7 (0x00007f03d7a88000)
        libTKLCAF.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKLCAF.so.7 (0x00007f03d77a0000)
        libTKVCAF.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKVCAF.so.7 (0x00007f03d7558000)
        libquazip5.so.1 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libquazip5.so.1 (0x00007f03d7310000)
        libGLU.so.1 => /usr/lib64/libGLU.so.1 (0x00007f03d7230000)
        libz.so.1 => /usr/lib64/libz.so.1 (0x00007f03d7210000)
        libsqlite3.so.0 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libsqlite3.so.0 (0x00007f03d6ef0000)
        libavformat.so.57 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libavformat.so.57 (0x00007f03d6ae0000)
        libavcodec.so.57 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libavcodec.so.57 (0x00007f03d55d8000)
        libavresample.so.3 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libavresample.so.3 (0x00007f03d53b8000)
        libavutil.so.55 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libavutil.so.55 (0x00007f03d5138000)
        libswresample.so.2 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libswresample.so.2 (0x00007f03d4f18000)
        libswscale.so.4 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libswscale.so.4 (0x00007f03d4c90000)
        libGL.so.1 => /usr/lib64/nvidia340/libGL.so.1 (0x00007f03d4940000)
        libQt5OpenGL.so.5 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libQt5OpenGL.so.5 (0x00007f03d46e8000)
        libQt5Charts.so.5 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libQt5Charts.so.5 (0x00007f03d4328000)
        libQt5Widgets.so.5 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libQt5Widgets.so.5 (0x00007f03d3ac8000)
        libQt5Gui.so.5 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libQt5Gui.so.5 (0x00007f03d31a8000)
        libQt5Network.so.5 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libQt5Network.so.5 (0x00007f03d2df8000)
        libQt5Core.so.5 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libQt5Core.so.5 (0x00007f03d2618000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f03d25f0000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00007f03d24a8000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007f03d22d8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f03dd138000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00007f03d22c8000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f03d22c0000)
        libstlvis.so => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libstlvis.so (0x00007f03d20b8000)
        libgeom2dvis.so => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libgeom2dvis.so (0x00007f03d1eb0000)
        libcsgvis.so => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libcsgvis.so (0x00007f03d1ca8000)
        libTKBool.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKBool.so.7 (0x00007f03d16a0000)
        libTKCAF.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKCAF.so.7 (0x00007f03d1400000)
        libTKCDF.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKCDF.so.7 (0x00007f03d11a8000)
        libTKG2d.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKG2d.so.7 (0x00007f03d0f48000)
        libTKGeomAlgo.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKGeomAlgo.so.7 (0x00007f03d0838000)
        libTKHLR.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKHLR.so.7 (0x00007f03d0510000)
        libTKOffset.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKOffset.so.7 (0x00007f03d01a0000)
        libTKService.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKService.so.7 (0x00007f03cff60000)
        libTKShHealing.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKShHealing.so.7 (0x00007f03cfad8000)
        libTKSTEP209.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKSTEP209.so.7 (0x00007f03cf828000)
        libTKSTEPAttr.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKSTEPAttr.so.7 (0x00007f03cf518000)
        libTKV3d.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKV3d.so.7 (0x00007f03cef98000)
        libTKXCAF.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKXCAF.so.7 (0x00007f03cecd8000)
        libTKXDEIGES.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKXDEIGES.so.7 (0x00007f03ceab8000)
        libTKXDESTEP.so.7 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libTKXDESTEP.so.7 (0x00007f03ce7f8000)
        libXmu.so.6 => /usr/lib64/libXmu.so.6 (0x00007f03ce7d8000)
        libstl.so => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libstl.so (0x00007f03ce570000)
        libgeom2d.so => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libgeom2d.so (0x00007f03ce350000)
        libvisual.so => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libvisual.so (0x00007f03ce110000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f03cdf88000)
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f03cdf68000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f03cde28000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f03cde10000)
        libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007f03cddf8000)
        libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f03cdd48000)
        libbluray.so.2 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libbluray.so.2 (0x00007f03cdaf0000)
        libgnutls.so.30 => /usr/lib64/libgnutls.so.30 (0x00007f03cd910000)
        libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007f03cd8f8000)
        libwebp.so.6 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libwebp.so.6 (0x00007f03cd698000)
        libva.so.2 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libva.so.2 (0x00007f03cd470000)
        libzvbi.so.0 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libzvbi.so.0 (0x00007f03cd1e0000)
        libxvidcore.so.4 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libxvidcore.so.4 (0x00007f03ccec8000)
        libx265.so.169 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libx265.so.169 (0x00007f03cbd60000)
        libx264.so.155 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libx264.so.155 (0x00007f03cb8a0000)
        libwebpmux.so.2 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libwebpmux.so.2 (0x00007f03cb690000)
        libvpx.so.4 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libvpx.so.4 (0x00007f03cb308000)
        libvorbisenc.so.2 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libvorbisenc.so.2 (0x00007f03cb058000)
        libvorbis.so.0 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libvorbis.so.0 (0x00007f03cae28000)
        libtwolame.so.0 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libtwolame.so.0 (0x00007f03cac00000)
        libtheoraenc.so.1 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libtheoraenc.so.1 (0x00007f03ca9c0000)
        libtheoradec.so.1 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libtheoradec.so.1 (0x00007f03ca7a0000)
        libspeex.so.1 => /usr/lib64/libspeex.so.1 (0x00007f03ca780000)
        libopus.so.0 => /usr/lib64/libopus.so.0 (0x00007f03ca720000)
        libopenjpeg.so.1 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libopenjpeg.so.1 (0x00007f03ca4f0000)
        libmp3lame.so.0 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libmp3lame.so.0 (0x00007f03ca278000)
        libgsm.so.1 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libgsm.so.1 (0x00007f03ca068000)
        libcelt0.so.2 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libcelt0.so.2 (0x00007f03c9e50000)
        liblzma.so.5 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/liblzma.so.5 (0x00007f03c9c10000)
        libvdpau.so.1 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libvdpau.so.1 (0x00007f03c9a08000)
        libva-x11.so.2 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libva-x11.so.2 (0x00007f03c9800000)
        libva-drm.so.2 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libva-drm.so.2 (0x00007f03c95f8000)
        libnvidia-tls.so.340.108 => /usr/lib64/nvidia340/tls/libnvidia-tls.so.340.108 (0x00007f03c93f0000)
        libnvidia-glcore.so.340.108 => /usr/lib64/nvidia340/libnvidia-glcore.so.340.108 (0x00007f03c67d8000)
        libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f03c6780000)
        libicui18n.so.56 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libicui18n.so.56 (0x00007f03c62e0000)
        libicuuc.so.56 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libicuuc.so.56 (0x00007f03c5f28000)
        libicudata.so.56 => /home/tiger/Work/Software/FEBIO/FEBIO 3.0/FEBioStudio/bin/./../lib/libicudata.so.56 (0x00007f03c4540000)
        libgthread-2.0.so.0 => /usr/lib64/libgthread-2.0.so.0 (0x00007f03c4538000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007f03c4418000)
        libXt.so.6 => /usr/lib64/libXt.so.6 (0x00007f03c43a8000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f03c4380000)
        libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007f03c4320000)
        libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007f03c41b8000)
        libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007f03c4170000)
        libp11-kit.so.0 => /usr/lib64/libp11-kit.so.0 (0x00007f03c4048000)
        libidn2.so.0 => /usr/lib64/libidn2.so.0 (0x00007f03c4028000)
        libunistring.so.2 => /usr/lib64/libunistring.so.2 (0x00007f03c3ea0000)
        libtasn1.so.6 => /usr/lib64/libtasn1.so.6 (0x00007f03c3e88000)
        libnettle.so.6 => /usr/lib64/libnettle.so.6 (0x00007f03c3e48000)
        libhogweed.so.4 => /usr/lib64/libhogweed.so.4 (0x00007f03c3e08000)
        libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007f03c3d88000)
        libintl.so.8 => /usr/lib64/libintl.so.8 (0x00007f03c3d78000)
        libnuma.so.1 => /usr/lib64/libnuma.so.1 (0x00007f03c3d68000)
        libogg.so.0 => /usr/lib64/libogg.so.0 (0x00007f03c3d58000)
        libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f03c3d50000)
        libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007f03c3d38000)
        libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f03c3c48000)
        libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f03c3c28000)
        libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007f03c3c20000)
        libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f03c3c10000)
        libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1 (0x00007f03c3c08000)
        libresolv.so.2 => /usr/lib64/libresolv.so.2 (0x00007f03c3be8000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f03c3b70000)
        libSM.so.6 => /usr/lib64/libSM.so.6 (0x00007f03c3b60000)
        libICE.so.6 => /usr/lib64/libICE.so.6 (0x00007f03c3b40000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f03c3b38000)
        libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00007f03c3b30000)
        libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f03c3b20000)
        libffi.so.6 => /usr/lib64/libffi.so.6 (0x00007f03c3b10000)
        libbsd.so.0 => /usr/lib64/libbsd.so.0 (0x00007f03c3af0000)

**Comment by michaelrossherron** [comment]
I have spent a couple of days working on this issue, and I haven't been able to make any headway on it. I created a virtual machine running Mageia in order to test out this bug, but I'm unable to reproduce it exactly how you're experiencing it. I am, however, unable to run FEBio Studio on Mageia for different (though probably related) reasons. 

At some point during the initialization of FEBio Studio on Mageia, despite everything that I've tried, it's attempting to load in some of the Qt5 libraries that ship with Mageia. The system libraries that it's linking to aren't direct dependencies of FEBio Studio, but are to be dependencies of some of its dependencies. The problem with this is that the Qt5 libraries that ship on Mageia are from an older version of Qt than the ones that we link to at build time, and so are incompatible. 

I've spent a couple of days trying everything that I can think of to get around this issue, but I've yet to find a solution. I will continue to try to resolve this issue, but as you are currently the only user that we have who is experiencing this issue, it will have to take a back seat for now. 

I have personally tested FEBio Studio on both Ubuntu and OpenSuse, and we have a number of users running it successfully on other common distributions. If possible for you, you may need to consider using one of these distributions to run our software. You could also attempt to compile the software yourself. Unfortunately, we don't yet have a build guide up for FEBio Studio, though I am currently working on finalizing a CMAKE script for it, and will hopefully be adding that finalized script along with a build guide to the github repository in the coming weeks. 

If you happen to find a solution to this issue on your own, please respond to this thread with your solution so that we can help anyone else who may have this issue in the future. 

Please let me know if you have any questions. 

Michael Herron

**Comment by heikostark** [comment]
Many thanks for your effort! Seems to be a typical problem of dependency hell.
I will just have to wait for an update of Mageia or your Cmake script. 

Best regards,
Heiko

**Comment by heikostark** [comment]
One possibility would be the static linking of libraries. This would make the program large, but it would not have to search for libraries on the system.

https://doc.qt.io/qt-5/linux-deployment.html#static-linking

Best regards,
Heiko

**Comment by michaelrossherron** [comment]
I attempted to get Qt5 to build statically a couple of years ago, and ran into a lot of problems. I can probably take another crack at it now though and see if I can get it to work this time. I will let you know if I'm able to get it to work.

Michael Herron
